// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserDirectory.API.DbContexts;

#nullable disable

namespace UserDirectory.API.Migrations
{
    [DbContext(typeof(UserContext))]
    partial class UserContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.24");

            modelBuilder.Entity("UserDirectory.API.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PinCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 20,
                            City = "Sydney",
                            Name = "John Doe",
                            PinCode = "1111",
                            State = "NSW"
                        },
                        new
                        {
                            Id = 2,
                            Age = 35,
                            City = "Melbourne",
                            Name = "Jane Doe",
                            PinCode = "2222",
                            State = "Victoria"
                        },
                        new
                        {
                            Id = 3,
                            Age = 29,
                            City = "Adelaide",
                            Name = "Tony Smith",
                            PinCode = "3333",
                            State = "South Australia"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
